name: venbo
favicon: null
layout_spectrum: 0.7282961346209049
typography_spectrum: 0.11542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#32405a'
    - '#6b788b'
    - '#abb4bd'
    - '#cecfd3'
  brandStrength: 0.9753620272967964
  lightness: 0.7456320750061423
  saturation: 0.8100560209713876
  rhythmicContrast: 0.28645462775602937
purpose: []
