name: venbo
favicon: null
layout_spectrum: 0.7282961346209049
typography_spectrum: 0.11542
title: 'Venbo.de '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1715'
    - '#9a815d'
    - '#472a20'
    - '#bfa16e'
    - '#705638'
  brandStrength: 0.9753620272967964
  lightness: 0.7456320750061423
  saturation: 0.8100560209713876
  rhythmicContrast: 0.28645462775602937
purpose: []
